repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.0
    hooks:
      - id: ruff-check
        name: ruff fix command
        args: [--fix, --exit-non-zero-on-fix]
        stages: [commit]
      - id: ruff-format
      - id: ruff-check
        name: ruff-check-only
        args: []