services:
  database:
    image: "postgres:latest"
    env_file:
      - .env.development
    ports:
      - "5439:5432"
    volumes:
      - db_data:/var/lib/postgresql

  backend:
    build:
      context: .
      dockerfile: ./dockerfiles/backend.dockerfile
    env_file:
      - .env.development
    environment:
      - PYTHONPATH=/app
    ports:
      - "8000:8000"
    depends_on:
      - database
    command:
      - "fastapi"
      - "dev"
      - "--host"
      - "0.0.0.0"
      - "app/main.py"
    volumes:
      - ./backend:/app
volumes:
  db_data:
